## Put your model args here
module:
  _target_: chemflow.model.lightning_module.LightningModule
  # args and kwargs 

  # The 'model' key below is an argument to your LightningModule
  model:
    _target_: chemflow.model.gnn.EGNNwithHeads
    _recursive_: false

    embedding_args: ${model.embedding}
    egnn_args: ${model.egnn}
    heads_args: ${model.heads}

embedding:
  _target_: chemflow.model.embedding.Embedding
  in_nf: 10
  out_nf: 32

egnn:
  _target_: src.external_code.egnn.EGNN
  in_node_nf: ${model.embedding.out_nf}
  hidden_nf: 64
  out_node_nf: 64
  in_edge_nf: 0
  n_layers: 3
  residual: True
  attention: False
  normalize: False
  tanh: False

heads:
  _target_: chemflow.model.heads.MultiHeadModule

  heads_configs:
    node_heads:
      node_classification:
        input_dim: ${model.egnn.out_node_nf}
        output_dim: 10
        hidden_dim: 32

      node_regression:
        input_dim: ${model.egnn.out_node_nf}
        output_dim: 1

    graph_heads:
      graph_classification:
        input_dim: ${model.egnn.out_node_nf}
        output_dim: 5
        hidden_dim: 32
        aggregation: mean

      graph_regression:
        input_dim: ${model.egnn.out_node_nf}
        output_dim: 1
        aggregation: sum
      
