## Put your model args here
module:
  _target_: chemflow.model.lightning_module.LightningModule
  # args and kwargs 

  model:
    _target_: chemflow.model.torch_model.TorchModel
    # args and kwargs
    example_arg: 1
    example_arg2: "example"

    