integrator:
  _target_: chemflow.flow_matching.integration.RateIntegrator
  vocab: ${data.vocab}
  distributions: None
  gmm_params: ${model.gmm_params}
  n_atoms_strategy: ${data.n_atoms_strategy}
  # strategy used for sampling time during **integration**
  # NOTE can be different from the time strategy used for the model (see below)
  time_strategy: log # "linear" or "log"
  num_integration_steps: 200
  ins_noise_scale: ${data.ins_noise_scale}
  del_schedule: ${data.interpolator.del_schedule}
  ins_schedule: ${data.interpolator.ins_schedule}
  sub_schedule: ${data.interpolator.sub_schedule}
  sub_e_schedule: ${data.interpolator.sub_e_schedule}